/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MediaFile {
  'originalName' : string,
  'contentType' : string,
  'file' : ExternalBlob,
}
export interface MessageView {
  'id' : bigint,
  'content' : string,
  'nickname' : string,
  'audio' : [] | [MediaFile],
  'video' : [] | [MediaFile],
  'isEdited' : boolean,
  'nonce' : [] | [string],
  'timestamp' : Time,
  'image' : [] | [MediaFile],
  'replyToId' : [] | [bigint],
  'reactions' : Array<Reaction>,
}
export interface Reaction { 'userId' : string, 'emoji' : string }
export type Time = bigint;
export interface UserProfile { 'nickname' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReaction' : ActorMethod<[string, bigint, string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[string, string], { 'joinCode' : string }>,
  'deleteMessage' : ActorMethod<[string, bigint], boolean>,
  'editMessage' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      [] | [MediaFile],
      [] | [MediaFile],
      [] | [MediaFile],
    ],
    boolean
  >,
  'fetchMessagesAfterId' : ActorMethod<[string, bigint], Array<MessageView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessageTTL' : ActorMethod<[], Time>,
  'getMessages' : ActorMethod<[string], Array<MessageView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[string, string], { 'nickname' : string }>,
  'pruneExpiredMessages' : ActorMethod<[], undefined>,
  'removeReaction' : ActorMethod<[string, bigint, string, string], boolean>,
  'roomExists' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [bigint],
      [] | [MediaFile],
      [] | [MediaFile],
      [] | [MediaFile],
      string,
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];